name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Start Backend
      run: npm run start:be &
    - name: Start Frontend
      run: npm run start:fe &
    - name: install playwright browsers
      run: npx playwright install
    - name: Execute the UI tests
      run: npm run test:ui
